# Configuration generated by setup.py for gluuotp python library
LDAP_URI = "ldaps://localhost:1636"
LDAP_USER = "cn=directory manager"
LDAP_PASS = "%(ldapPass)s"
BASE_DN = "ou=people,o=%(inumOrg)s,o=gluu"
